components:
  sber.astream:
    title: Компания Astream
    entity: component
  sber.astream.app:
    title: Слой прикладной архитектуры
    entity: component
  sber.astream.app.home_cinema:
    title: Продукт/Прикладной сервис Домашний кинотеатр
    entity: component
    aspects:
      - aspects_sber.astream.app.home_cinema.tv_streaming.multiplex1
      - aspects_sber.astream.app.home_cinema.tv_streaming
      - aspects_sber.astream.app.auth
      - aspects_sber.astream.app.home_cinema.search
      - aspects_sber.astream.app.home_cinema.media_storage
    links:
      - id: sber.astream.app.mediaplatform
        title: взаимодействие
        direction: <-->
    sber:
      type: service
      role_model: Централизованная
      criticality: Business Critical
      class: Иное
  sber.astream.app.mediaplatform:
    title: Медиаплатформа
    entity: component
    sber:
      type: service
      role_model: Централизованная
      criticality: Business Critical
      class: CMS (Content Management System)

  sber.astream.app.home_cinema.catalog:
    entity: component
    title: Сервис Каталог фильмов
    description: Каталог фильмов
    aspects:
      - aspects_sber.astream.app.home_cinema.media_storage
      - aspects_sber.astream.app.home_cinema.search
      - aspects_sber.astream.app.home_cinema.tv_streaming
      - aspects_sber.astream.app.home_cinema.tv_streaming.multiplex1
    sber:
      type: service
      criticality: Business Critical
      role_model: Централизованная
      class: Продуктовая фабрика (основная деятельность)

  sber.astream.app.home_cinema.payments:
    entity: component
    title: Сервис платежей
    description: Осуществление платежей пользователей за подписки
    sber:
      type: service
      criticality: Business Operational
      role_model: Централизованная
      class: Иное

  sber.astream.app.home_cinema.canals:
    entity: component
    title: Сервис трансляции ТВ-Каналов
    description: Трансляция ТВ-каналов
    aspects:
      - aspects_sber.astream.app.home_cinema.tv_streaming
      - aspects_sber.astream.app.home_cinema.tv_streaming.multiplex1
    sber:
      type: service
      criticality: Business Operational
      role_model: Централизованная
      class: Иное

  sber.astream.app.home_cinema.auth:
    entity: component
    title: Cервис аутентификации
    description: Авторизация пользователей для доступа к Домашнему кинотеарту
    aspects:
      - aspects_sber.astream.app.auth
    sber:
      type: service
      criticality: Business Critical
      role_model: Централизованная
      class: Клиентский профиль (Customer Information File)

  sber.astream.app.erp1c:
    entity: component
    title: 1C ERP
    aspects:
      - aspects_sber.astream.app.accounting
    sber:
      type: service
      role_model: Нецентрализованная
      criticality: Office Productivity
      class: Бухгалтерия и финансы
